// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_w2hjCCnX_F8oqDw0uPnmTQ-CCtbqcoQ',
    appId: '1:934159213204:web:3618df2097faf8984a4a81',
    messagingSenderId: '934159213204',
    projectId: 'fire-setup-33812',
    authDomain: 'fire-setup-33812.firebaseapp.com',
    storageBucket: 'fire-setup-33812.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSDXvYT2tMJnETYFM_0-nBeAPn4nH2i0',
    appId: '1:934159213204:android:40137d3142aa895c4a4a81',
    messagingSenderId: '934159213204',
    projectId: 'fire-setup-33812',
    storageBucket: 'fire-setup-33812.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_w2hjCCnX_F8oqDw0uPnmTQ-CCtbqcoQ',
    appId: '1:934159213204:web:a29a11ce3ecb6eb24a4a81',
    messagingSenderId: '934159213204',
    projectId: 'fire-setup-33812',
    authDomain: 'fire-setup-33812.firebaseapp.com',
    storageBucket: 'fire-setup-33812.firebasestorage.app',
  );
}
